### ISSUE TITLE
About CB513 database

### ISSUE THREAD

**Issue by anonymous530** [alrojo/RNNProteins#2]
Can I ask a question? How can I get the CB513 database?

**Comment by anonymous530** [comment]
When I downloaded from this site: http://www.princeton.edu/~jzthree/datasets/ICML2014/. The compressed file doesn't work. It was broken and just can't be extracted.

**Comment by alrojo** [comment]
This project should have automatic download, so if you just run `train.py` it should work.

Alternatively, check out the data loader: https://github.com/alrojo/CB513/blob/master/data.py

**Comment by AndrewSoul** [comment]
It seems that the download_train.sh script also doesn't work.  Because there's something wrong in the site http://www.princeton.edu/~jzthree/datasets/ICML2014/.

**Comment by anonymous530** [comment]
OK. Thanks.

**Comment by alrojo** [comment]
I can see that the original author recently uploaded a new 1.1G file into the [folder](http://www.princeton.edu/~jzthree/datasets/ICML2014/).
That might be what is causing the trouble.
Feel free to PR your solution.

I will close this issue for now, thanks for pointing it out.
